name: Main

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  ROBOHELP_PATH: 'C:\Program Files\Adobe\Adobe RoboHelp 2020\RoboHelp.exe'
  PROJECT_PATH: '${{ github.workspace }}\test.rhp'
  OUTPUT_PATH: '${{ github.workspace }}\output'
  OUTPUT_PRESET: 'Responsive HTML5'

jobs:
  build:
    name: Build
    runs-on: [self-hosted]
    timeout-minutes: 5
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Make output directory
        id: make
        run: mkdir ${{ env.OUTPUT_PATH }}

      - name: Build
        id: build
        run: >
          & "${{ env.ROBOHELP_PATH }}"
          --cl "${{ env.PROJECT_PATH }}"
          -o "${{ env.OUTPUT_PRESET }}"	
          -p "${{ env.OUTPUT_PATH }}"

      - name: Check Output
        id: check
        run: >
          ls ${{ env.OUTPUT_PATH }}